name: Build and Deploy

on:
   push:
      tags:
         - 'v[0-9]+.[0-9]+.[0-9]+'

   # Allow running manually from the actions tab
   workflow_dispatch:

concurrency:
   group: "release"
   cancel-in-progress: true

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         -  uses: actions/checkout@master
            with:
               lfs: true

         -  name: Build Module
            run: |
               node --version
               npm --version
               npm i
               npm run build-module

         -  name: Archive Release
            run: |
               pushd _dist/plutonium-scenes
               zip -r ../../plutonium-scenes.zip .
               popd

         -  name: Upload Release
            run: |
               echo "${{github.ref_name}}" > NOTES_FILE.md
               gh release create "Dev Tooling ${{github.ref_name}}" --title "${{github.ref_name}}" --notes-file NOTES_FILE.md plutonium-scenes.zip _dist/plutonium-scenes/module.json
            env:
               GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
